
import { Link } from 'react-router-dom';
import { 
  Sun, 
  Battery, 
  Lightbulb, 
  ChevronRight,
  Wrench,
  Zap,
  ArrowRight 
} from 'lucide-react';
import AnimatedSection from '../AnimatedSection';
import ProductCard from './ProductCard';

const ProductsSection = () => {
  const products = [
    {
      icon: <Sun className="w-12 h-12" />,
      title: "Solar Panel",
      description: "High-efficiency photovoltaic panels that convert sunlight into electricity for your home or business.",
      link: "/products/solar-panel"
    },
    {
      icon: <Battery className="w-12 h-12" />,
      title: "Energy Storage Battery",
      description: "Advanced battery systems that store excess solar energy for use when the sun isn't shining.",
      link: "/products/energy-storage"
    },
    {
      icon: <Lightbulb className="w-12 h-12" />,
      title: "Inverter",
      description: "Converts DC electricity generated by solar panels into AC electricity for your appliances.",
      link: "/products/inverter"
    },
    {
      icon: <Zap className="w-12 h-12" />,
      title: "PV Water Pump",
      description: "Solar-powered water pumping solutions for agricultural irrigation and water supply.",
      link: "/products/pv-water-pump"
    },
    {
      icon: <Wrench className="w-12 h-12" />,
      title: "PV-ESS Integrated Cabinet",
      description: "All-in-one solutions that combine solar power generation with energy storage capabilities.",
      link: "/products/pv-ess-cabinet"
    },
    {
      icon: <svg className="w-12 h-12" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M22 6C22 4.9 21.1 4 20 4H15V2H9V4H4C2.9 4 2 4.9 2 6V20C2 21.1 2.9 22 4 22H20C21.1 22 22 21.1 22 20V6ZM20 6V9H4V6H20ZM4 20V11H20V20H4Z" fill="currentColor"/>
              <path d="M12 12H6V14H12V12Z" fill="currentColor"/>
              <path d="M18 12H14V14H18V12Z" fill="currentColor"/>
              <path d="M12 16H6V18H12V16Z" fill="currentColor"/>
              <path d="M18 16H14V18H18V16Z" fill="currentColor"/>
            </svg>,
      title: "Cable Rack",
      description: "Professional cable management systems for clean and safe solar installations.",
      link: "/products/cable-rack"
    }
  ];

  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4">
        <AnimatedSection>
          <div className="text-center mb-16">
            <span className="section-subheading">Our Product Range</span>
            <h2 className="section-heading">One-Stop Solar Solution</h2>
            <p className="max-w-3xl mx-auto text-gray-600 mt-4">
              Our comprehensive range of solar energy products designed to provide efficient, 
              reliable, and sustainable power solutions for homes and businesses.
            </p>
          </div>
        </AnimatedSection>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {products.map((product, index) => (
            <AnimatedSection key={index} animation="slide-up" delay={(index + 1) * 100}>
              <ProductCard 
                icon={product.icon}
                title={product.title}
                description={product.description}
                link={product.link}
              />
            </AnimatedSection>
          ))}
        </div>

        <div className="text-center mt-12">
          <Link 
            to="/products" 
            className="inline-flex items-center bg-primary text-white py-3 px-8 rounded-lg font-medium transition-all hover:bg-primary/90"
          >
            View All Products <ArrowRight className="w-5 h-5 ml-2" />
          </Link>
        </div>
      </div>
    </section>
  );
};

export default ProductsSection;
